name: Docker Image CI

on:
  push:
    branches: "main"
    paths:
      - 'docker/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
  CHAT_ID: "${{ secrets.CHAT_ID }}"
  TOPIC_ID: "${{ secrets.TOPIC_ID }}"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: "Cancelling duplicate workflow runs"
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        all_but_latest: true
        access_token: ${{ github.token }}
    
    # Notify to Specific Topic of a Supergroup
    - name: Notify User on Telegram
      run: |
            curl -s -X POST https://api.telegram.org/bot$BOT_TOKEN/sendMessage -F chat_id=$CHAT_ID -F message_thread_id=$TOPIC_ID \
                      -F text='Docker Image Push Successfully'





